export const CLASS_LIST = {
    REQ_GET_CLASSLIST: 'REQ_GET_CLASSLIST',
    REQ_GET_CLASSLIST_SUCCESS: 'REQ_GET_CLASSLIST_SUCCESS',
    REQ_GET_CLASSLIST_FAIL: 'REQ_GET_CLASSLIST_FAIL',

    REQ_GET_CLASS_DETAIL: 'REQ_GET_CLASS_DETAIL',
    REQ_GET_CLASS_DETAIL_SUCCESS: 'REQ_GET_CLASS_DETAIL_SUCCESS',
    REQ_GET_CLASS_DETAIL_FAIL: 'REQ_GET_CLASS_DETAIL_FAIL',

    REQ_UPDATE_CLASS: 'REQ_UPDATE_CLASS',
    REQ_UPDATE_CLASS_SUCCESS: 'REQ_UPDATE_CLASS_SUCCESS',
    REQ_UPDATE_CLASS_FAIL: 'REQ_UPDATE_CLASS_FAIL',
    REQ_RESET_CLASS_DETAIL_STATUS: 'REQ_RESET_CLASS_DETAIL_STATUS',

    REQ_GET_CLASS_SESSION: 'REQ_GET_CLASS_SESSION',
    REQ_GET_CLASS_SESSION_SUCCESS: 'REQ_GET_CLASS_SESSION_SUCCESS',
    REQ_GET_CLASS_SESSION_FAIL: 'REQ_GET_CLASS_SESSION_FAIL',
};
