export const SET_GOOGLE = {
    REQ_GOOGLE_API_AND_SERVICES: 'REQ_GOOGLE_API_AND_SERVICES',

    REQ_GOOGLE_API_FILE: 'REQ_GOOGLE_API_FILE',

    REQ_GOOGLE_DRIVE_GET_LIST_SUCCESS: 'REQ_GOOGLE_DRIVE_SUCCESS',
    REQ_GOOGLE_DRIVE_GET_LIST_FAIL: 'REQ_GOOGLE_DRIVE_FAIL',

    REQ_GOOGLE_DRIVE_UPDATE_FILE: 'REQ_GOOGLE_DRIVE_UPDATE_FILE',
    REQ_GOOGLE_DRIVE_UPDATE_FILE_SUCCESS:
        'REQ_GOOGLE_DRIVE_UPDATE_FILE_SUCCESS',

    REQ_GOOGLE_DRIVE_UPDATE_FILE_FAIL: 'REQ_GOOGLE_DRIVE_UPDATE_FILE_FAIL',
    REQ_GOOGLE_DRIVE_UPDATE_FILE_RESET: 'REQ_GOOGLE_DRIVE_UPDATE_FILE_RESET',

    REQ_GOOGLE_UPLOAD_NEW_FOLDER_SUCCESS:
        'REQ_GOOGLE_UPLOAD_NEW_FOLDER_SUCCESS',
    REQ_GOOGLE_UPLOAD_NEW_FOLDER_FAIL: 'REQ_GOOGLE_UPLOAD_NEW_FOLDER_FAIL',

    REQ_GOOGLE_UPLOAD_FILE_SUCCESS: 'REQ_GOOGLE_UPLOAD_FILE_SUCCESS',
    REQ_GOOGLE_UPLOAD_FILE_FAIL: 'REQ_GOOGLE_UPLOAD_FILE_FAIL',

    REQ_GOOGLE_GET_LOCAL_FILE: 'REQ_GOOGLE_GET_LOCAL_FILE',
    REQ_GOOGLE_REMOVE_LOCAL_FILE: 'REQ_GOOGLE_REMOVE_LOCAL_FILE',
    REQ_GOOGLE_GET_FILE: 'REQ_GOOGLE_GET_FILE',
    REQ_GOOGLE_GET_FILE_SUCCESS: 'REQ_GOOGLE_GET_FILE_SUCCESS',
    REQ_GOOGLE_GET_FILE_FAIL: 'REQ_GOOGLE_GET_FILE_FAIL',

    REQ_GOOGLE_CONTEXT_ACTION_SET: 'REQ_GOOGLE_CONTEXT_ACTION_SET',

    REQ_GOOGLE_SET_TREE_FOLDER: 'REQ_GOOGLE_SET_TREE_FOLDER',
    REQ_GOOGLE_REMOVE_TREE_FOLDER: 'REQ_GOOGLE_SET_TREE_FOLDER',

    REQ_GOOGLE_ACTION_UPLOAD: 'REQ_GOOGLE_ACTION_UPLOAD',

    REQ_GOOGLE_PARENT_DROP: 'REQ_GOOGLE_PARENT_DROP',
};

export const SET_GOOGLE_SERVER_SIDE = {
    REQ_GOOGLE_SERVER_SIDE_API_AND_SERVICES:
        'REQ_GOOGLE_SERVER_SIDE_API_AND_SERVICES',

    REQ_GET_DRIVE_AUTHENTICATE_URL_OAUTH2_SUCCESS:
        'REQ_GET_DRIVE_AUTHENTICATE_URL_OAUTH2_SUCCESS',
    REQ_GET_DRIVE_AUTHENTICATE_URL_OAUTH2_FAIL:
        'REQ_GET_DRIVE_AUTHENTICATE_URL_OAUTH2_FAIL',

    REQ_AUTHENTICATE_WITH_DRIVE_OAUTH2_SUCCESS:
        'REQ_AUTHENTICATE_WITH_DRIVE_OAUTH2_SUCCESS',
    REQ_AUTHENTICATE_WITH_DRIVE_OAUTH2_FAIL:
        'REQ_AUTHENTICATE_WITH_DRIVE_OAUTH2_FAIL',

    REQ_GET_DRIVE_CREDENTIALS_OF_WORKSPACE_OAUTH2_SUCCESS:
        'REQ_GET_DRIVE_CREDENTIALS_OF_WORKSPACE_OAUTH2_SUCCESS',
    REQ_GET_DRIVE_CREDENTIALS_OF_WORKSPACE_OAUTH2_FAIL:
        'REQ_GET_DRIVE_CREDENTIALS_OF_WORKSPACE_OAUTH2_FAIL',
};
