export const SET_H5P_CONTENT_LIST = {
    REQ_H5P_CONTENT_LIST: 'REQ_H5P_CONTENT_LIST',
    REQ_H5P_CONTENT_LIST_SUCCESS: 'REQ_H5P_CONTENT_LIST_SUCCESS',
    REQ_H5P_CONTENT_LIST_FAIL: 'REQ_H5P_CONTENT_LIST_FAIL',
    REQ_H5P_SORT_LIST: 'REQ_H5P_SORT_LIST',
};

export const SET_H5P_EDITOR = {
    REQ_H5P_EDITOR: 'REQ_H5P_EDITOR',
    REQ_H5P_EDITOR_SUCCESS: 'REQ_H5P_EDITOR_SUCCESS',
    REQ_H5P_EDITOR_FAIL: 'REQ_H5P_EDITOR_FAIL',
};

export const SET_H5P_PLAYER = {
    REQ_H5P_PLAYER: 'REQ_H5P_PLAYER',
    REQ_H5P_PLAYER_SUCCESS: 'REQ_H5P_PLAYER_SUCCESS',
    REQ_H5P_PLAYER_FAIL: 'REQ_H5P_PLAYER_FAIL',
};

export const SET_H5P_STATUS = {
    REQ_H5P_STATUS: 'REQ_H5P_STATUS',
    REQ_H5P_STATUS_SUCCESS: 'REQ_H5P_STATUS_SUCCESS',
    REQ_H5P_STATUS_FAIL: 'REQ_H5P_STATUS_FAIL',
    REQ_H5P_RESET_STATUS: 'REQ_H5P_RESET_STATUS',
};

export const SET_H5P_UPDATE = {
    REQ_H5P_ADD_TAG_SUCCESS: 'REQ_H5P_ADD_TAG_SUCCESS',
    REQ_H5P_ADD_TAG_FAIL: 'REQ_H5P_ADD_TAG_FAIL',
};

export const H5P_CONTENT = {
    REQ_SET_CURRENT_H5P_INIT: 'REQ_SET_CURRENT_H5P_INIT',
    REQ_SET_CURRENT_H5P: 'REQ_SET_CURRENT_H5P',
    REQ_SET_CURRENT_H5P_ERROR: 'REQ_SET_CURRENT_H5P_ERROR',
    REQ_H5P_RECOVER: 'REQ_H5P_RECOVER',
};
