export const SET_MENU_LEFT = {
    REQ_GET_FILE_UPLOAD: 'REQ_GET_FILE_UPLOAD',
    REQ_REMOVE_FILE_UPLOAD: 'REQ_REMOVE_FILE_UPLOAD',
    REQ_GET_FOLDER_NAME_UPLOAD: 'REQ_GET_FOLDER_NAME_UPLOAD',
    REQ_REMOVE_FOLDER_NAME_UPLOAD: 'REQ_REMOVE_FOLDER_NAME_UPLOAD',
};
