export const GET_REPORT = {
    REQ_GET_REPORT_GENERAL: 'REQ_GET_REPORT_GENERAL',
    REQ_GET_REPORT_GENERAL_FINISH: 'REQ_GET_REPORT_GENERAL_FINISH',
    REQ_GET_REPORT_GENERAL_FAILED: 'REQ_GET_REPORT_GENERAL_FAILED',
    REQ_GET_REPORT_TEACHER: 'REQ_GET_REPORT_TEACHER',
    REQ_GET_REPORT_TEACHER_FINISH: 'REQ_GET_REPORT_TEACHER_FINISH',
    REQ_GET_REPORT_TEACHER_FAILED: 'REQ_GET_REPORT_TEACHER_FAILED',
};
