export const SET_USER = {
    REQ_USER: 'REQ_USER',
    REQ_USER_SUCCESS: 'REQ_USER_SUCCESS',
    REQ_USER_FAIL: 'REQ_USER_FAIL',

    REQ_UPDATE_USER: 'REQ_USER',
    REQ_UPDATE_USER_SUCCESS: 'REQ_USER_SUCCESS',
    REQ_UPDATE_USER_FAIL: 'REQ_USER_FAIL',
    REQ_RESET_RESULT: 'REQ_RESET_RESULT',

    REQ_UPLOAD_AVATAR: 'REQ_UPLOAD_AVATAR',
    REQ_REFRESH_UPLOAD_AVATAR_PROCESS: 'REQ_REFRESH_UPLOAD_AVATAR_PROCESS',

    REQ_UPLOAD_AVATAR_FORM_DATA_SUCCESS: 'REQ_UPLOAD_AVATAR_FORM_DATA_SUCCESS',
    REQ_UPLOAD_AVATAR_FORM_DATA_FAIL: 'REQ_UPLOAD_AVATAR_FORM_DATA_FAIL',

    REQ_UPLOAD_AVATAR_FINAL_SUCCESS: 'REQ_UPLOAD_AVATAR_FINAL_SUCCESS',
    REQ_UPLOAD_AVATAR_FINAL_FAIL: 'REQ_UPLOAD_AVATAR_FINAL_FAIL',

    REQ_TOKEN_EXPIRED: 'REQ_TOKEN_EXPIRED',
    REQ_TOKEN_ACTIVATED: 'REQ_TOKEN_ACTIVATED',

    REQ_USER_ROLE: 'REQ_USER_ROLE',
    REQ_SET_CREATOR: 'REQ_SET_CREATOR',

    RESET_USER_INFORMATION: 'RESET_USER_INFORMATION',
};
