export const H5P_LIBRARY: Record<any, any> = {
    InteractiveVideo: 'Interactive Video',
    CoursePresentation: 'Course Presentation',
    MultiChoice: 'Multiple Choice',
    QuestionSet: 'Quiz (Question Set)',
    Blanks: 'Fill in the Blanks',
    DragText: 'Drag the Words',
    Column: 'Column',
    DragQuestion: 'Drag and Drop',
    ImageHotspots: 'Image Hotspots',
    Accordion: 'Accordion',
    Dialogcards: 'Dialog Cards',
    SingleChoiceSet: 'Single Choice Set',
    MemoryGame: 'Memory Game',
    Flashcards: 'Flashcards',
    DocumentationTool: 'Documentation Tool',
    ArithmeticQuiz: 'ArithmeticQuiz',
    Chart: 'Chart',
    Collage: 'Collage',
    ImageHotspotQuestion: 'Find the Hotspot',
    GuessTheAnswer: 'Guess the Answer',
    IFrameEmbed: 'Iframe Embedder',
    MarkTheWords: 'Mark the Words',
    PersonalityQuiz: 'Personality Quiz',
    Questionnaire: 'Questionnaire',
    Summary: 'Summary',
    Timeline: 'Timeline',
    TrueFalse: 'True/False Question',
    ImageMultipleHotspotQuestion: 'Find Multiple Hotspots',
    ImageJuxtaposition: 'Image Juxtaposition',
    Audio: 'Audio',
    AudioRecorder: 'Audio Recorder',
    SpeakTheWords: 'Speak the Words',
    Agamotto: ' Agamotto (Image Blender)',
    ImageSequencing: 'Image Sequencing',
    SpeakTheWordsSet: 'Speak the Words Set',
    ImageSlider: 'Image Slider',
    Essay: 'Essay',
    ImagePair: 'Image Pairing',
    Dictation: 'Dictation',
    BranchingScenario: 'Branching Scenario',
    ThreeImage: 'Virtual Tour (360)',
    FindTheWords: 'Find the words',
    InteractiveBook: 'Interactive Book',
    KewArCode: 'KewAr Code',
    AdventCalendar: 'Advent Calendar',
    Crossword: 'Crossword',
    SortParagraphs: 'Sort the Paragraphs',
    MultiMediaChoice: 'Image Choice',
};

export const H5P_STATUS: Record<any, any> = {
    pending: 'Pending',
    draft: 'Draft',
    public: 'Publish',
    archive: 'Archive',
    trash: 'Trash',
};
