export const LESSON_ACTIONS = {
    SET_TITLE: 'SET_TITLE',
    SET_PAGE: 'SET_PAGE',
    SET_SELECTED_TAG: 'SET_SELECTED_TAG',
    SET_SELECTED_AUTHOR: 'SET_SELECTED_AUTHOR',
    SET_FILTER_MENU: 'SET_FILTER_MENU',
    SET_ORDER: 'SET_ORDER',
};
